### ISSUE TITLE
Windows 빌드 오류

### ISSUE THREAD

**Issue by diskhkme** [jdeokkim/mvp-demo#3]
building 설명에 있는 Windows 기준 가이드를 따랐을 때 경로 참조 문제로 빌드가 안되는 것 같은데 확인 해 주실 수 있으실까요?

**Comment by jdeokkim** [comment]
안녕하세요, 교수님! 

말씀해주신 내용 참고하여 README.md 파일 업데이트하였습니다. (https://github.com/jdeokkim/mvp-demo/commit/01994e970387096a59443716ba3f826d08166133)

감사합니다! 😄

**Comment by jdeokkim** [comment]
@diskhkme 혹시 WebAssembly 빌드 필요하시면 [여기](https://jdeokkim.github.io/projects/mvp-demo/)에서 확인하실 수 있습니다!
